name: eslint check
on: [push]
jobs:
  Eslint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci

      - uses: mikeal/npx@master

      - name: check eslint
        run: npx eslint $(git diff --name-only --diff-filter=d HEAD | grep -E '\.(js|jsx|ts|tsx)$' | xargs)
